--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 29/10/2022 4:56:57 CH
-- Server version: 8.0.30
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE `misa.web09.qtkd.sondxt`;

--
-- Drop table `department`
--
DROP TABLE IF EXISTS department;

--
-- Drop table `employee`
--
DROP TABLE IF EXISTS employee;

--
-- Drop table `jobposition`
--
DROP TABLE IF EXISTS jobposition;

--
-- Set default database
--
USE `misa.web09.qtkd.sondxt`;

--
-- Create table `jobposition`
--
CREATE TABLE jobposition (
  JobPositionID char(36) NOT NULL DEFAULT '' COMMENT 'ID c?a v? tr',
  JobPositionCode varchar(20) NOT NULL DEFAULT '' COMMENT 'M? v? tr',
  JobPositionName varchar(255) NOT NULL DEFAULT '' COMMENT 'T?n v? tr',
  CreatedDate datetime DEFAULT NULL COMMENT 'Th?i gian t?o',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Ng??i t?o',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Th?i gian ch?nh s?a g?n nh?t',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Ng??i ch?nh s?a g?n nh?t',
  PRIMARY KEY (JobPositionID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'b?ng th?ng tin c?ng vi?c';

--
-- Create index `JobPositionCode` on table `jobposition`
--
ALTER TABLE jobposition
ADD UNIQUE INDEX JobPositionCode (JobPositionCode);

--
-- Create table `employee`
--
CREATE TABLE employee (
  EmployeeID char(255) NOT NULL DEFAULT '' COMMENT 'ID nh?n vi',
  EmployeeCode varchar(20) NOT NULL DEFAULT '' COMMENT 'M? nh?n vi',
  FullName varchar(100) NOT NULL DEFAULT '' COMMENT 'H? v? t?n nh?n vi',
  DateOfBirth datetime DEFAULT NULL COMMENT 'Ng?y sinh',
  Gender tinyint DEFAULT NULL COMMENT 'Gi?i t?nh (0: N?, 1: Nam)',
  Email varchar(50) DEFAULT NULL COMMENT 'Email nh?n vi',
  Address varchar(255) DEFAULT NULL COMMENT '??a ch?',
  IdentityNumber varchar(25) NOT NULL DEFAULT '' COMMENT 'S? CMND',
  IdentityDate datetime DEFAULT NULL COMMENT 'Ng?y c?p CMND',
  IdentityPlace varchar(100) DEFAULT NULL COMMENT 'N?i c?p CMND',
  DepartmentID varchar(36) DEFAULT NULL COMMENT 'ID ??n v?',
  DepartmentName varchar(100) DEFAULT NULL COMMENT 'T?n ??n v?',
  PositionID char(36) DEFAULT NULL COMMENT 'ID ch?c v?',
  PositionName varchar(100) DEFAULT NULL COMMENT 'T?n ch?c v?',
  Salary int DEFAULT NULL COMMENT 'l??ng nh?n vi',
  BankAccountNumber varchar(16) DEFAULT NULL COMMENT 'S? t?i kho?n ng?n h?ng',
  BankName varchar(100) DEFAULT NULL COMMENT 'T?n ng?n h?ng',
  BankBranch varchar(255) DEFAULT NULL COMMENT 'Chi nh?nh ng?n h?ng',
  TelephoneNumber varchar(50) DEFAULT NULL COMMENT 'S? ?i?n tho?i di ??ng',
  PhoneNumber varchar(50) DEFAULT NULL COMMENT 'S? ?i?n tho?i nh?n vi',
  CreatedDate datetime DEFAULT NULL COMMENT 'Th?i gian t?o',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Ng??i t?o',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Th?i gian ch?nh s?a g?n nh?t',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Ng??i ch?nh s?a g?n nh?t',
  PRIMARY KEY (EmployeeID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'B?ng th?ng itn nh?n vi';

--
-- Create index `EmployeeCode` on table `employee`
--
ALTER TABLE employee
ADD UNIQUE INDEX EmployeeCode (EmployeeCode);

--
-- Create index `IX_employee_FullName` on table `employee`
--
ALTER TABLE employee
ADD INDEX IX_employee_FullName (FullName);

--
-- Create index `IX_employee_PhoneNumber` on table `employee`
--
ALTER TABLE employee
ADD INDEX IX_employee_PhoneNumber (PhoneNumber);

--
-- Create foreign key
--
ALTER TABLE employee
ADD CONSTRAINT FK_employee_jobposition_JobPositionID FOREIGN KEY (PositionID)
REFERENCES jobposition (JobPositionID);

--
-- Create table `department`
--
CREATE TABLE department (
  DepartmenId char(36) NOT NULL DEFAULT '' COMMENT 'ID ph?ng ban',
  DepartmentCode varchar(20) NOT NULL DEFAULT '' COMMENT 'M? ph?ng ban',
  DepartmentName varchar(255) NOT NULL DEFAULT '' COMMENT 'T?n ph?ng ban',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ng?y t?o ph?ng ban',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Ng??i t?o ph?ng ban',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ng?y s?a g?n nh?t',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Ng??i s?a g?n nh?t',
  PRIMARY KEY (DepartmenId)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'B?ng th?ng tin ph?ng ban';

-- 
-- Dumping data for table jobposition
--
INSERT INTO jobposition VALUES
('1fb9af36-5769-11ed-adf9-38d57a64d68a', 'j12313', 'sown', '2022-10-29 16:07:33', 'sown', '2022-10-29 16:07:33', 'sown'),
('7d3b2e4c-576d-11ed-adf9-38d57a64d68a', 'j123456', 'qu?n l?', '2022-10-29 16:38:48', 'son', '2022-10-29 16:38:48', 'sown');

-- 
-- Dumping data for table employee
--
INSERT INTO employee VALUES
('09763a2f-576e-11ed-adf9-38d57a64d68a', 'nv12345', 'ho va ten', '0000-00-00 00:00:00', NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2022-10-29 16:42:43', 'sown', '2022-10-29 16:42:43', 'sown');

-- 
-- Dumping data for table department
--
INSERT INTO department VALUES
('03587280-576d-11ed-adf9-38d57a64d68a', 'dp1234', 'ph?ng qu?n l?', '2022-10-29 16:35:23', 'sown', '2022-10-29 16:35:23', 'sown');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;